# Generated by Django 4.0.1 on 2022-01-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_like_like_post_rename_liked_user_like_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
